### ISSUE TITLE
Missing await statements in GarbageManager

### ISSUE THREAD

**Issue by Manuel-Innovapps** [iAlexeyProkhorov/qBoSlider#14]
![image](https://user-images.githubusercontent.com/54266094/212248134-69301d8b-edc8-4743-bc87-7c9b9e4aabde.png)

**Comment by iAlexeyProkhorov** [comment]
Hi! 
Thank you for your message. I'll try to fix this in next plugin version 😉

**Comment by iAlexeyProkhorov** [comment]
Hi! Fixed at new version 1.4.3 😉
