### ISSUE TITLE
qBoSlider (df702ef) not work in NopCommerce 4.70.5 

### ISSUE THREAD

**Issue by rkravcov** [iAlexeyProkhorov/qBoSlider#23]
admin panel qBoSlider (df702ef) have only one checkbox "Use static cache", "Save" and nothing more.
![image](https://github.com/user-attachments/assets/d02db5ed-dd4f-4c90-8638-427f27e06be2). Not page for add pictures and set settings.

**Comment by iAlexeyProkhorov** [comment]
Hi! @rkravcov 
Thank you for your message.

Please read note in yellow rectangle located under caption 'Configure - qBoSlider'. You can read [Get Started](https://github.com/iAlexeyProkhorov/qBoSlider/wiki/Get-started) menu.
Find qBoSlider at left menu, to configure widget zones and sliders. It should be located in "Third part plugins" menu.

Write here if you have some more questions 😉

**Comment by rkravcov** [comment]
Дякую! )))
