### ISSUE TITLE
bugs 

### ISSUE THREAD

**Issue by UAsoftwaredeveloper** [iAlexeyProkhorov/qBoSlider#6]
.Net 4.40 and bugs for .net core 5
has lots of errors and bugs hence it s not running condition.

**Comment by iAlexeyProkhorov** [comment]
Hi! Thank you for your message.
Can you write more details please?

**Comment by UAsoftwaredeveloper** [comment]
Irrelevant code approach with nop 4.40 assemblies.
In plugin install class

**Comment by iAlexeyProkhorov** [comment]
Hi! Unfortunately I can't fix any issue, if I don't see it.
Please write about some concrete issue or exception that you find.

Thank you :)

**Comment by UAsoftwaredeveloper** [comment]
i am not sure how will you feel to connect over what's app.
